// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWcaj21FdRZebqGpmOEQP-hQNlpg6s_Us',
    appId: '1:102193542944:web:6cdf3fd0347332b7438945',
    messagingSenderId: '102193542944',
    projectId: 'first-app-cfbf7',
    authDomain: 'first-app-cfbf7.firebaseapp.com',
    databaseURL: 'https://first-app-cfbf7-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-cfbf7.firebasestorage.app',
    measurementId: 'G-Y4YWB4STJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDydcq-5o3xojNKSwB0s89F-t0UXVnTOrQ',
    appId: '1:102193542944:android:968ba25f8dfd6554438945',
    messagingSenderId: '102193542944',
    projectId: 'first-app-cfbf7',
    databaseURL: 'https://first-app-cfbf7-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-cfbf7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWcaj21FdRZebqGpmOEQP-hQNlpg6s_Us',
    appId: '1:102193542944:web:6cdf3fd0347332b7438945',
    messagingSenderId: '102193542944',
    projectId: 'first-app-cfbf7',
    authDomain: 'first-app-cfbf7.firebaseapp.com',
    databaseURL: 'https://first-app-cfbf7-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-cfbf7.firebasestorage.app',
    measurementId: 'G-Y4YWB4STJ1',
  );

}