// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWcaj21FdRZebqGpmOEQP-hQNlpg6s_Us',
    appId: '1:102193542944:web:97ba5aa97e6f6011438945',
    messagingSenderId: '102193542944',
    projectId: 'first-app-cfbf7',
    authDomain: 'first-app-cfbf7.firebaseapp.com',
    databaseURL: 'https://first-app-cfbf7-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-cfbf7.firebasestorage.app',
    measurementId: 'G-WBW6LF1TPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDydcq-5o3xojNKSwB0s89F-t0UXVnTOrQ',
    appId: '1:102193542944:android:0a9a40f23cd22f21438945',
    messagingSenderId: '102193542944',
    projectId: 'first-app-cfbf7',
    databaseURL: 'https://first-app-cfbf7-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-cfbf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADyflmf4q_JJ2ktrMFiPCPUMRAE00YRSk',
    appId: '1:102193542944:ios:1c0084dd60ef6823438945',
    messagingSenderId: '102193542944',
    projectId: 'first-app-cfbf7',
    databaseURL: 'https://first-app-cfbf7-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-cfbf7.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADyflmf4q_JJ2ktrMFiPCPUMRAE00YRSk',
    appId: '1:102193542944:ios:1c0084dd60ef6823438945',
    messagingSenderId: '102193542944',
    projectId: 'first-app-cfbf7',
    databaseURL: 'https://first-app-cfbf7-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-cfbf7.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWcaj21FdRZebqGpmOEQP-hQNlpg6s_Us',
    appId: '1:102193542944:web:789b36de61bd3086438945',
    messagingSenderId: '102193542944',
    projectId: 'first-app-cfbf7',
    authDomain: 'first-app-cfbf7.firebaseapp.com',
    databaseURL: 'https://first-app-cfbf7-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-cfbf7.firebasestorage.app',
    measurementId: 'G-7DPXPPX9BK',
  );

}